import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Container from "@/components/container";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog App with Next.js",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated, getUser } = getKindeServerSession();
  const isAuth = await isAuthenticated();
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-zinc-300 bg-zinc-900 bg-opacity-95 min-h-screen`}
      >
        <Container>
          <Header isAuth={isAuth} />

          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
